upload_max_filesize=50M
post_max_size=50M
memory_limit=512M
max_execution_time=300
date.timezone=Asia/Phnom_Penh

; Production
display_errors=Off
log_errors=On
expose_php=Off

; Performance
realpath_cache_size=4096K
realpath_cache_ttl=600

; OPcache
opcache.enable=1
opcache.enable_cli=1
opcache.memory_consumption=256
opcache.interned_strings_buffer=16
opcache.max_accelerated_files=20000
opcache.validate_timestamps=1
opcache.revalidate_freq=2
opcache.save_comments=1
opcache.fast_shutdown=1
